package Form;

import Connect.DatabaseHelper;
import Dao.BangCongDAO;
import Dao.ChiTietHoaDonDAO;
import Dao.HoaDonDAO;
import Dao.PhieuNhapDAO;
import Dao.SachDAO;
import Entity.BangCong;
import Entity.PhieuNhap;
import com.raven.datechooser.DateBetween;
import com.raven.datechooser.DateChooser;
import com.raven.datechooser.listener.DateChooserAction;
import com.raven.datechooser.listener.DateChooserAdapter;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Year;
import java.time.YearMonth;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

public class FormThongKe extends javax.swing.JPanel {

    
    ZoneId zoneId = ZoneId.of("Asia/Ho_Chi_Minh" );
    YearMonth yearMonthNow = YearMonth.now( zoneId );
    YearMonth yearMonthPrevious = yearMonthNow.minusMonths( 1 );
    LocalDate firstOfMonth = yearMonthPrevious.atDay( 1 );
    LocalDate lastOfMonth = yearMonthPrevious.atEndOfMonth();
    private DateChooser chDate = new DateChooser();
    ChiTietHoaDonDAO cthdDao = new ChiTietHoaDonDAO();
    SachDAO sachDao = new SachDAO();
    HoaDonDAO hdDao = new HoaDonDAO();
    PhieuNhapDAO pnDao = new PhieuNhapDAO();
    BangCongDAO bcDao = new BangCongDAO();
    String dateFrom = firstOfMonth.toString();
    String dateTo  = lastOfMonth.toString();
    
    public FormThongKe() throws SQLException {
        initComponents();
        fillDataDoanhThu();
        fillDataSachBan();
        updateLabel();
        chDate.setTextField(txtDate);
        chDate.setDateSelectionMode(DateChooser.DateSelectionMode.BETWEEN_DATE_SELECTED);
        chDate.addActionDateChooserListener(new DateChooserAdapter() {
            @Override
            public void dateBetweenChanged(DateBetween date, DateChooserAction action) {
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                dateFrom = df.format(date.getFromDate());
                dateTo = df.format(date.getToDate());
                try {
                    fillDataSachBanTheoNgay(dateFrom, dateTo);
                    fillDataDoanhThuTheoNgay(dateFrom, dateTo);
                    updateLabelTheoNgay(dateFrom,dateTo);
                } catch (SQLException ex) {
                    Logger.getLogger(FormThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachBan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTong = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblDon = new javax.swing.JLabel();
        txtDate = new Swing.TextField();
        lblTimTheoNgay = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTienNhap = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblLoiNhuan = new javax.swing.JLabel();
        btnBieuDoDoanhThu = new Swing.ButtonGradient();
        btnBieuDoSach = new Swing.ButtonGradient();

        setBackground(new java.awt.Color(255, 255, 255));

        tblSachBan.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblSachBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sách", "Số lượng đã bán"
            }
        ));
        tblSachBan.setRequestFocusEnabled(false);
        tblSachBan.setRowHeight(30);
        tblSachBan.setSelectionBackground(new java.awt.Color(237, 237, 237));
        jScrollPane1.setViewportView(tblSachBan);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setFocusable(false);
        jPanel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doanh thu");

        lblTong.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblTong.setForeground(new java.awt.Color(255, 255, 255));
        lblTong.setText("VND");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTong)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTong)
                .addGap(18, 18, 18))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tổng số đơn");

        lblDon.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblDon.setForeground(new java.awt.Color(255, 255, 255));
        lblDon.setText("VND");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDon)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDon)
                .addGap(19, 19, 19))
        );

        lblTimTheoNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_30px.png"))); // NOI18N
        lblTimTheoNgay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblDoanhThu.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày ", "Doanh Thu"
            }
        ));
        tblDoanhThu.setRequestFocusEnabled(false);
        tblDoanhThu.setRowHeight(30);
        tblDoanhThu.setSelectionBackground(new java.awt.Color(237, 237, 237));
        jScrollPane2.setViewportView(tblDoanhThu);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tiền nhập sách");

        lblTienNhap.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblTienNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTienNhap.setText("VND");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTienNhap)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTienNhap)
                .addGap(19, 19, 19))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lợi nhuận");

        lblLoiNhuan.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblLoiNhuan.setForeground(new java.awt.Color(255, 255, 255));
        lblLoiNhuan.setText("VND");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoiNhuan)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblLoiNhuan)
                .addGap(19, 19, 19))
        );

        btnBieuDoDoanhThu.setText("Doanh thu");
        btnBieuDoDoanhThu.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBieuDoDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBieuDoDoanhThuMousePressed(evt);
            }
        });
        btnBieuDoDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBieuDoDoanhThuActionPerformed(evt);
            }
        });

        btnBieuDoSach.setText("Sách đã bán");
        btnBieuDoSach.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBieuDoSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBieuDoSachMousePressed(evt);
            }
        });
        btnBieuDoSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBieuDoSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBieuDoDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnBieuDoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTimTheoNgay)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(516, 516, 516))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTimTheoNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBieuDoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBieuDoDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(30, 30, 30))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBieuDoDoanhThuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBieuDoDoanhThuMousePressed
                try {
            Year thisYear = Year.now();
            String sql = "SELECT MONTH(NgayLapHoaDon), SUM(TongTien) FROM HoaDon\n" +
                         "WHERE YEAR(NgayLapHoaDon) = '" + thisYear +"'" +
                         "GROUP BY MONTH(NgayLapHoaDon)" ;
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(DatabaseHelper.getConnection(),sql);          
            JFreeChart chart = ChartFactory.createBarChart3D("Doanh thu năm " + thisYear, "Tháng", "Doanh thu", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer bar = null;
            bar = new BarRenderer();
            CategoryPlot catPlot = new CategoryPlot();
            catPlot.setRangeGridlinePaint(Color.BLACK);
            
            ChartFrame frame = new ChartFrame("Biểu đồ",chart);
            frame.setVisible(true);
            frame.setSize(960,600);
            frame.setLocationRelativeTo(null);
        } catch (Exception e) {
            System.out.println("Loi thong ke doanh thu: " + e.toString());
        }
    }//GEN-LAST:event_btnBieuDoDoanhThuMousePressed

    private void btnBieuDoSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBieuDoSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBieuDoSachActionPerformed

    private void btnBieuDoSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBieuDoSachMousePressed
                if(txtDate.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày để thống kê", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }else {
            try {
            String sql = "SELECT S.TenSach, SUM(C.SoLuong) FROM ChiTietHoaDon C\n" +
                         "JOIN Sach S ON S.MaSach = C.MaSach\n" +
                         "JOIN HoaDon D ON D.MaHoaDon = C.MaHoaDon\n" +
                         "WHERE D.NgayLapHoaDon BETWEEN '" +dateFrom + "' AND '" +dateTo + "'\n" +
                         "GROUP BY S.TenSach";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(DatabaseHelper.getConnection(),sql);          
            JFreeChart chart = ChartFactory.createBarChart3D("Số lượng sách bán", "Tháng", "Doanh thu", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer bar = null;
            bar = new BarRenderer();
            CategoryPlot catPlot = new CategoryPlot();
            catPlot.setRangeGridlinePaint(Color.BLACK);
            
            ChartFrame frame = new ChartFrame("Biểu đồ",chart);
            frame.setVisible(true);
            frame.setSize(960,600);
            frame.setLocationRelativeTo(null);
            } catch (Exception e) {
                    System.out.println("Loi thong ke sach ban: " + e.toString());
            }
        }
    }//GEN-LAST:event_btnBieuDoSachMousePressed

    private void btnBieuDoDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBieuDoDoanhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBieuDoDoanhThuActionPerformed

    public void fillDataSachBan() throws SQLException{
        java.sql.Connection con;
        ResultSet rs = null;
        Statement stm = null;
        DefaultTableModel model = (DefaultTableModel) tblSachBan.getModel();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for(int i=0;i<2;i++){
            tblSachBan.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        model.setRowCount(0); 
        String sql = "SELECT C.MaSach, S.TenSach, SUM(C.SoLuong) AS TONG FROM ChiTietHoaDon C\n" +
                            "JOIN Sach S ON S.MaSach = C.MaSach\n" +
                            "GROUP BY C.MaSach, S.TenSach";
        con = Connect.DatabaseHelper.getConnection();
        stm = con.createStatement();
        rs = stm.executeQuery(sql);
        while(rs.next()){  
            Object[] rowData = new Object[6];
            rowData[0] = rs.getString(2);
            rowData[1] = rs.getString(3);
            model.addRow(rowData);
        }
    }
    
    public void fillDataSachBanTheoNgay(String dateFrom, String dateTo) throws SQLException{
        java.sql.Connection con;
        ResultSet rs = null;
        Statement stm = null;
        DefaultTableModel model = (DefaultTableModel) tblSachBan.getModel();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for(int i=0;i<2;i++){
            tblSachBan.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        model.setRowCount(0); 
        String sql = "SELECT C.MaSach, S.TenSach, SUM(C.SoLuong) FROM ChiTietHoaDon C \n" +
                        "JOIN Sach S ON S.MaSach = C.MaSach\n" +
                        "JOIN HoaDon H ON H.MaHoaDon = C.MaHoaDon\n" +
                        "WHERE H.NgayLapHoaDon BETWEEN '" + dateFrom + "' AND '" + dateTo + "'\n" +
                        "GROUP BY C.MaSach, S.TenSach";
        con = Connect.DatabaseHelper.getConnection();
        stm = con.createStatement();
        rs = stm.executeQuery(sql);
        while(rs.next()){  
            Object[] rowData = new Object[6];
            rowData[0] = rs.getString(2);
            rowData[1] = rs.getString(3);
            model.addRow(rowData);
        }
    }
    
    public void fillDataDoanhThu() throws SQLException{
        java.sql.Connection con;
        ResultSet rs = null;
        Statement stm = null;
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for(int i=0;i<2;i++){
            tblDoanhThu.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        model.setRowCount(0);
        String sql = "SELECT NgayLapHoaDon, SUM(TongTien) FROM HoaDon\n" +
                        "GROUP BY NgayLapHoaDon";
        con = Connect.DatabaseHelper.getConnection();
        stm = con.createStatement();
        rs = stm.executeQuery(sql);
        while(rs.next()){  
            Object[] rowData = new Object[6];
            rowData[0] = rs.getString(1);
            rowData[1] = Double.parseDouble(rs.getString(2));
            model.addRow(rowData);
        }
    }
    
    public void fillDataDoanhThuTheoNgay(String dateFrom, String dateTo) throws SQLException{
        java.sql.Connection con;
        ResultSet rs = null;
        Statement stm = null;
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for(int i=0;i<2;i++){
            tblDoanhThu.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        model.setRowCount(0);
        String sql = "SELECT NgayLapHoaDon, SUM(TongTien) FROM HoaDon WHERE NgayLapHoaDon BETWEEN '" + dateFrom + "' and '" + dateTo + "'\n" +
                        "GROUP BY NgayLapHoaDon";
        con = Connect.DatabaseHelper.getConnection();
        stm = con.createStatement();
        rs = stm.executeQuery(sql);
        while(rs.next()){  
            Object[] rowData = new Object[6];
            rowData[0] = rs.getString(1);
            rowData[1] = rs.getString(2);
            model.addRow(rowData);
        }
    }
    
    public void updateLabel(){
        String soDon = Integer.toString(hdDao.layDSHoaDon().size());
        double tongTien = 0;
        double tongTienNhap = 0;
        for(int i = 0;i<tblDoanhThu.getRowCount();i++){
            tongTien = tongTien + Double.parseDouble(tblDoanhThu.getValueAt(i, 1).toString());
        }
        for (PhieuNhap phieuNhap : pnDao.layDSPhieuNhap()) {
            tongTienNhap = tongTienNhap + phieuNhap.getTongTien();
        }
        lblDon.setText(soDon);
        lblTong.setText(Double.toString(tongTien));
        lblTienNhap.setText(Double.toString(tongTienNhap));
        lblLoiNhuan.setText(Double.toString(tongTien - tongTienNhap));
    }
    
    public void updateLabelTheoNgay(String dateFrom, String dateTo){
        String soDon = Integer.toString(hdDao.timHoaDon(dateFrom, dateTo).size());
        double tongTien = 0;
        double tongTienNhap = 0;
        for(int i = 0;i<tblDoanhThu.getRowCount();i++){
            tongTien = tongTien + Double.parseDouble(tblDoanhThu.getValueAt(i, 1).toString());
        }
        for (PhieuNhap phieuNhap : pnDao.timPhieuNhap(dateFrom, dateTo)) {
            tongTienNhap = tongTienNhap + phieuNhap.getTongTien();
        }
        lblDon.setText(soDon);
        lblTong.setText(Double.toString(tongTien));
        lblTienNhap.setText(Double.toString(tongTienNhap));
        lblLoiNhuan.setText(Double.toString(tongTien - tongTienNhap));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.ButtonGradient btnBieuDoDoanhThu;
    private Swing.ButtonGradient btnBieuDoSach;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDon;
    private javax.swing.JLabel lblLoiNhuan;
    private javax.swing.JLabel lblTienNhap;
    private javax.swing.JLabel lblTimTheoNgay;
    private javax.swing.JLabel lblTong;
    private javax.swing.JTable tblDoanhThu;
    private javax.swing.JTable tblSachBan;
    private Swing.TextField txtDate;
    // End of variables declaration//GEN-END:variables
}
